"""Follow up prompt column  in AiAgent added

Revision ID: a3ffe30f155c
Revises: d85003ce767e
Create Date: 2025-11-03 11:09:55.342675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ffe30f155c'
down_revision: Union[str, Sequence[str], None] = 'd85003ce767e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('prompt_template1', sa.Text(), nullable=True))
    op.add_column('ai_agents', sa.Column('prompt_template2', sa.Text(), nullable=True))
    op.drop_column('ai_agents', 'prompt_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('prompt_template', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ai_agents', 'prompt_template2')
    op.drop_column('ai_agents', 'prompt_template1')
    # ### end Alembic commands ###
