"""Removed GroupAndAgent, AiAgent and made changes to AgentMessage

Revision ID: a42490b6e598
Revises: b284448a1a02
Create Date: 2025-10-31 23:43:48.053497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42490b6e598'
down_revision: Union[str, Sequence[str], None] = 'b284448a1a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS ai_agents CASCADE')
    op.execute('DROP TABLE IF EXISTS group_and_agent_associations CASCADE')
    op.add_column('model_messages', sa.Column('agent_name', sa.String(), nullable=False))
    # op.drop_constraint(op.f('model_messages_agent_id_fkey'), 'model_messages', type_='foreignkey')
    op.drop_column('model_messages', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_messages', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('model_messages_agent_id_fkey'), 'model_messages', 'ai_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_messages', 'agent_name')
    op.create_table('group_and_agent_associations',
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], name=op.f('group_and_agent_associations_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('group_and_agent_associations_group_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('group_and_agent_associations_pkey')),
    sa.UniqueConstraint('group_id', 'agent_id', name=op.f('group_and_agent_associations_group_id_agent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_group_and_agent_associations_id'), 'group_and_agent_associations', ['id'], unique=False)
    op.create_table('ai_agents',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_agents_pkey'))
    )
    op.create_index(op.f('ix_ai_agents_name'), 'ai_agents', ['name'], unique=True)
    op.create_index(op.f('ix_ai_agents_id'), 'ai_agents', ['id'], unique=False)
    # ### end Alembic commands ###
