"""Added GroupAndAgent and AiAgent table

Revision ID: d85003ce767e
Revises: a42490b6e598
Create Date: 2025-11-02 16:12:45.130666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85003ce767e'
down_revision: Union[str, Sequence[str], None] = 'a42490b6e598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agents_id'), 'ai_agents', ['id'], unique=False)
    op.create_index(op.f('ix_ai_agents_name'), 'ai_agents', ['name'], unique=True)
    op.create_table('group_and_agent_associations',
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'agent_id')
    )
    op.create_index(op.f('ix_group_and_agent_associations_id'), 'group_and_agent_associations', ['id'], unique=False)
    op.add_column('model_messages', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'model_messages', 'ai_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_messages', 'agent_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_messages', sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_messages', type_='foreignkey')
    op.drop_column('model_messages', 'agent_id')
    op.drop_index(op.f('ix_group_and_agent_associations_id'), table_name='group_and_agent_associations')
    op.drop_table('group_and_agent_associations')
    op.drop_index(op.f('ix_ai_agents_name'), table_name='ai_agents')
    op.drop_index(op.f('ix_ai_agents_id'), table_name='ai_agents')
    op.drop_table('ai_agents')
    # ### end Alembic commands ###
